load("@contrib_rules_jvm//java:defs.bzl", "java_junit5_test")
load("@rules_java//java:java_library.bzl", "java_library")

package(
    default_visibility = ["//caching:all_caching"],
)

java_library(
    name = "test_utils",
    srcs = ["src/TestUtils.java"],
    testonly = True,
    deps = [
        "//caching/util:test_util",
        "@com_google_protobuf_protobuf_java",
        "@maven//:com_google_code_findbugs_jsr305",
        "@maven//:com_google_guava_guava",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_scala_lang_modules_scala_collection_compat_2_12",
        "@maven//:org_scala_lang_scala_library",
        "@scala_proto_rules_grpc_api",
        "@scala_proto_rules_grpc_netty",
        "@scala_proto_rules_grpc_stub",
        "@scala_proto_rules_scalapb_runtime",
    ],
)

java_junit5_test(
    name = "test_utils_test",
    srcs = ["test/TestUtilsTest.java"],
    data = [":test_data"],
    runtime_deps = [
        "@contrib_rules_jvm_deps//:org_junit_jupiter_junit_jupiter_engine",
        "@contrib_rules_jvm_deps//:org_junit_platform_junit_platform_launcher",
        "@contrib_rules_jvm_deps//:org_junit_platform_junit_platform_reporting",
    ],
    size = "small",
    test_class = "com.databricks.caching.util.javaapi.TestUtilsTest",
    deps = [
        ":test_utils",
        "//caching/util/javaapi/test/proto:test_message_proto_java_lib",
        "@com_google_protobuf_protobuf_java",
        "@contrib_rules_jvm_deps//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_assertj_assertj_core",
    ],
)

filegroup(
    name = "test_data",
    srcs = glob(["test/data/*.textproto"]),
)
