load("@rules_scala//scala:scala.bzl", "scala_library")

package(
    default_visibility = ["//dicer:internal"],
)

scala_library(
    name = "slicelet_conf_impl",
    srcs = ["src/SliceletConfImpl.scala"],
    deps = [
        "//dicer/external:conf",
        "//wrappers/conf:core",
        "//wrappers/conf:current_project",
        "//wrappers/conf:project",
        "//wrappers/conf:project-conf",
        "//wrappers/conf:raw_config_singleton",
        "//wrappers/rpc:rpc_tls",
        "@maven//:com_typesafe_config",
    ],
)

scala_library(
    name = "clerk_conf_impl",
    srcs = ["src/ClerkConfImpl.scala"],
    visibility = ["//dicer:internal"],
    deps = [
        "//dicer/external:conf",
        "//wrappers/conf:core",
        "//wrappers/conf:current_project",
        "//wrappers/conf:project",
        "//wrappers/conf:project-conf",
        "//wrappers/conf:raw_config_singleton",
        "//wrappers/rpc:rpc_tls",
        "@maven//:com_typesafe_config",
    ],
)
